import React from 'react';
import { Download, FileText, Image as ImageIcon, RotateCcw, ShieldAlert, CheckCircle2 } from 'lucide-react';
import CompareSlider from '../components/CompareSlider.jsx';
import { resultFileUrl } from '../api/srmApi.js';

function Metric({ label, value, note }) { return <div className="stat-card"><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className="text-2xl font-bold font-mono text-cyan-300 mt-2">{value ?? '—'}</div>{note && <div className="text-xs text-slate-600 mt-1">{note}</div>}</div>; }

export default function ResultsDashboard({ job, results, report, onReset }) {
  const outputs = results.outputs || {};
  const file = path => resultFileUrl(job.job_id, path);
  const reportUrl = file(outputs.report || 'report/report.json');
  const original = file(outputs.original_preview);
  const sr = file(outputs.super_resolution_preview);
  const srTif = file(report.outputs?.super_resolution || 'super_resolution/sr.tif');
  return <main className="min-h-screen" style={{ background: 'radial-gradient(ellipse 80% 30% at 50% 0%, rgba(6,182,212,0.08), transparent 70%), #050a14' }}>
    <header className="sticky-header px-6 md:px-12 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: 'linear-gradient(135deg,#0891b2,#1d4ed8)' }}><CheckCircle2 className="w-4 h-4 text-white" /></div><div><div className="font-bold text-white">PixelSight</div><div className="text-[10px] uppercase tracking-widest text-emerald-400">Processing complete</div></div></div><button className="btn-ghost" onClick={onReset}><RotateCcw className="w-4 h-4" /> New image</button></header>
    <div className="max-w-5xl mx-auto px-6 py-12 space-y-12">
      <section><div className="text-xs text-cyan-400 uppercase tracking-[0.22em] font-bold mb-4">Job {job.job_id}</div><h1 className="text-4xl font-bold text-white">A real model output, ready to inspect.</h1><p className="text-slate-400 mt-3 max-w-2xl">LDSR-S2 produced a 4x super-resolved representation (~2.5m equivalent) from the uploaded Sentinel-2-compatible raster.</p></section>
      <section><div className="flex items-end justify-between mb-5"><div><h2 className="text-2xl font-bold text-white">Before and after</h2><p className="text-sm text-slate-500 mt-1">Drag across the image to compare the original preview and SR preview.</p></div><a className="btn-ghost" href={sr} download><Download className="w-4 h-4" /> Preview PNG</a></div><div className="card overflow-hidden"><CompareSlider beforeSrc={original} afterSrc={sr} /><div className="px-5 py-3 text-xs text-slate-500 border-t border-white/[0.05]">Input: 10m native resolution · Output: 4x super-resolved representation (~2.5m equivalent)</div></div></section>
      <section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="Model" value="LDSR-S2" note="real checkpoint" /><Metric label="Sampling" value="100" note="diffusion steps" /><Metric label="Scale" value="4x" note="128 → 512 pixels" /><Metric label="Runtime" value={`${Number(report.runtime?.seconds || 0).toFixed(1)}s`} note={report.runtime?.device || 'device unknown'} /></section>
      <section className="grid md:grid-cols-[1fr_0.85fr] gap-6"><div className="card p-6"><div className="flex items-center gap-2 text-white font-semibold mb-5"><FileText className="w-4 h-4 text-cyan-400" /> Generated report</div><div className="space-y-3 text-sm"><div className="flex justify-between gap-4"><span className="text-slate-500">Input bands</span><span className="font-mono text-slate-200">{report.input?.band_names?.join(' / ')}</span></div><div className="flex justify-between gap-4"><span className="text-slate-500">Input size</span><span className="font-mono text-slate-200">{report.input?.width} × {report.input?.height}</span></div><div className="flex justify-between gap-4"><span className="text-slate-500">CRS</span><span className="font-mono text-slate-200">{report.input?.crs}</span></div><div className="flex justify-between gap-4"><span className="text-slate-500">Evaluation</span><span className="text-amber-300">Reference unavailable</span></div></div><a className="btn-primary mt-7 w-full" href={reportUrl} download="pixelsight-report.json"><Download className="w-4 h-4" /> Download JSON report</a></div><div className="card p-6"><div className="flex items-center gap-2 text-white font-semibold mb-5"><ShieldAlert className="w-4 h-4 text-amber-400" /> Scientific status</div><p className="text-sm text-slate-400 leading-relaxed">PSNR, SSIM, and SAM remain null because no valid high-resolution reference was supplied. The returned product is not observed 2.5m imagery.</p><div className="mt-5 space-y-2">{(report.scientific_limitations || []).map(item => <div key={item} className="text-xs text-slate-500 leading-relaxed">• {item}</div>)}</div></div></section>
      <section className="flex flex-wrap gap-3 pb-16"><a className="btn-ghost" href={srTif} download><ImageIcon className="w-4 h-4" /> Download SR GeoTIFF</a><a className="btn-ghost" href={original} download><Download className="w-4 h-4" /> Download original preview</a></section>
    </div>
  </main>;
}
